-- Baseline schema for identity.
--
-- Generated by deploy/squash-baseline.py from the 2 migrations it replaces, by running them
-- against an empty Postgres 16 and dumping the result, then replaying this file into a second empty
-- database and requiring the two dumps to match. Do not hand-edit: regenerate, or add a V2.
--
-- Extensions are created with IF NOT EXISTS, which works whoever runs this. citext, pgcrypto,
-- pg_trgm and unaccent are all trusted extensions, so the owner of the database can install them
-- without being a superuser; and where an administrator has created them already, these statements
-- skip with a notice rather than checking a privilege. See deploy/RUNBOOK-rds.md.
--
-- A database that already ran the old V1 will fail validation against this file, because the
-- checksum for version 1 has changed. That is intended: these databases are being recreated, and a
-- developer's local copy wants dropping rather than migrating.

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_challenges (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    purpose character varying(32) NOT NULL,
    user_id uuid,
    destination public.citext NOT NULL,
    secret_hash character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 5 NOT NULL,
    ip_address character varying(45),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid,
    CONSTRAINT ck_auth_challenges_attempts CHECK (((attempts >= 0) AND (max_attempts > 0))),
    CONSTRAINT ck_auth_challenges_purpose CHECK (((purpose)::text = ANY ((ARRAY['MAGIC_LINK'::character varying, 'EMAIL_OTP'::character varying, 'SMS_OTP'::character varying, 'WHATSAPP_OTP'::character varying, 'PASSWORD_RESET'::character varying, 'EMAIL_VERIFY'::character varying])::text[])))
);


--
-- Name: auth_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_identities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    user_id uuid NOT NULL,
    provider character varying(32) NOT NULL,
    provider_subject character varying(255) NOT NULL,
    provider_email public.citext,
    raw_profile jsonb DEFAULT '{}'::jsonb NOT NULL,
    linked_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid,
    CONSTRAINT ck_auth_identities_provider CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'MICROSOFT'::character varying, 'GITHUB'::character varying, 'SAML'::character varying])::text[])))
);


--
-- Name: device_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    user_id uuid NOT NULL,
    device_id character varying(128),
    device_name character varying(160),
    device_type character varying(24) DEFAULT 'WEB'::character varying NOT NULL,
    user_agent character varying(500),
    ip_address character varying(45),
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone,
    revoked_reason character varying(64),
    cookie_token_hash character varying(64),
    cookie_expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid,
    CONSTRAINT ck_device_sessions_type CHECK (((device_type)::text = ANY ((ARRAY['WEB'::character varying, 'IOS'::character varying, 'ANDROID'::character varying, 'API'::character varying])::text[])))
);


--
-- Name: oauth2_authorization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth2_authorization (
    id character varying(100) NOT NULL,
    registered_client_id character varying(100) NOT NULL,
    principal_name character varying(200) NOT NULL,
    authorization_grant_type character varying(100) NOT NULL,
    authorized_scopes character varying(1000) DEFAULT NULL::character varying,
    attributes text,
    state character varying(500) DEFAULT NULL::character varying,
    authorization_code_value text,
    authorization_code_issued_at timestamp with time zone,
    authorization_code_expires_at timestamp with time zone,
    authorization_code_metadata text,
    access_token_value text,
    access_token_issued_at timestamp with time zone,
    access_token_expires_at timestamp with time zone,
    access_token_metadata text,
    access_token_type character varying(100) DEFAULT NULL::character varying,
    access_token_scopes character varying(1000) DEFAULT NULL::character varying,
    oidc_id_token_value text,
    oidc_id_token_issued_at timestamp with time zone,
    oidc_id_token_expires_at timestamp with time zone,
    oidc_id_token_metadata text,
    refresh_token_value text,
    refresh_token_issued_at timestamp with time zone,
    refresh_token_expires_at timestamp with time zone,
    refresh_token_metadata text,
    user_code_value text,
    user_code_issued_at timestamp with time zone,
    user_code_expires_at timestamp with time zone,
    user_code_metadata text,
    device_code_value text,
    device_code_issued_at timestamp with time zone,
    device_code_expires_at timestamp with time zone,
    device_code_metadata text
);


--
-- Name: oauth2_authorization_consent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth2_authorization_consent (
    registered_client_id character varying(100) NOT NULL,
    principal_name character varying(200) NOT NULL,
    authorities character varying(1000) NOT NULL
);


--
-- Name: oauth2_registered_client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth2_registered_client (
    id character varying(100) NOT NULL,
    client_id character varying(100) NOT NULL,
    client_id_issued_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret character varying(200) DEFAULT NULL::character varying,
    client_secret_expires_at timestamp with time zone,
    client_name character varying(200) NOT NULL,
    client_authentication_methods character varying(1000) NOT NULL,
    authorization_grant_types character varying(1000) NOT NULL,
    redirect_uris character varying(1000) DEFAULT NULL::character varying,
    post_logout_redirect_uris character varying(1000) DEFAULT NULL::character varying,
    scopes character varying(1000) NOT NULL,
    client_settings character varying(2000) NOT NULL,
    token_settings character varying(2000) NOT NULL
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    user_id uuid NOT NULL,
    session_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    replaced_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    email public.citext NOT NULL,
    email_verified_at timestamp with time zone,
    phone character varying(32),
    phone_verified_at timestamp with time zone,
    password_hash character varying(120),
    password_changed_at timestamp with time zone,
    full_name character varying(160) NOT NULL,
    display_name character varying(80),
    avatar_url character varying(500),
    job_title character varying(120),
    timezone character varying(64) DEFAULT 'Asia/Kolkata'::character varying NOT NULL,
    locale character varying(16) DEFAULT 'en-IN'::character varying NOT NULL,
    status character varying(24) DEFAULT 'ACTIVE'::character varying NOT NULL,
    platform_admin boolean DEFAULT false NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    last_active_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_users_failed_attempts CHECK ((failed_login_attempts >= 0)),
    CONSTRAINT ck_users_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INVITED'::character varying, 'DISABLED'::character varying, 'LOCKED'::character varying])::text[])))
);


--
-- Data for Name: auth_challenges; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: auth_identities; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: device_sessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: oauth2_authorization; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: oauth2_authorization_consent; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: oauth2_registered_client; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: auth_challenges auth_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_challenges
    ADD CONSTRAINT auth_challenges_pkey PRIMARY KEY (id);


--
-- Name: auth_identities auth_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_identities
    ADD CONSTRAINT auth_identities_pkey PRIMARY KEY (id);


--
-- Name: device_sessions device_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_sessions
    ADD CONSTRAINT device_sessions_pkey PRIMARY KEY (id);


--
-- Name: oauth2_authorization_consent oauth2_authorization_consent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth2_authorization_consent
    ADD CONSTRAINT oauth2_authorization_consent_pkey PRIMARY KEY (registered_client_id, principal_name);


--
-- Name: oauth2_authorization oauth2_authorization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth2_authorization
    ADD CONSTRAINT oauth2_authorization_pkey PRIMARY KEY (id);


--
-- Name: oauth2_registered_client oauth2_registered_client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth2_registered_client
    ADD CONSTRAINT oauth2_registered_client_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: auth_identities uq_auth_identities_provider_subject; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_identities
    ADD CONSTRAINT uq_auth_identities_provider_subject UNIQUE (provider, provider_subject);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: ix_auth_challenges_destination; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auth_challenges_destination ON public.auth_challenges USING btree (destination, purpose, created_at DESC) WHERE (consumed_at IS NULL);


--
-- Name: ix_auth_challenges_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auth_challenges_lookup ON public.auth_challenges USING btree (secret_hash, purpose) WHERE (consumed_at IS NULL);


--
-- Name: ix_auth_identities_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auth_identities_user ON public.auth_identities USING btree (user_id);


--
-- Name: ix_device_sessions_user_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_device_sessions_user_active ON public.device_sessions USING btree (user_id) WHERE (revoked_at IS NULL);


--
-- Name: ix_oauth2_authorization_access; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth2_authorization_access ON public.oauth2_authorization USING btree (access_token_value);


--
-- Name: ix_oauth2_authorization_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth2_authorization_code ON public.oauth2_authorization USING btree (authorization_code_value);


--
-- Name: ix_oauth2_authorization_principal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth2_authorization_principal ON public.oauth2_authorization USING btree (principal_name);


--
-- Name: ix_oauth2_authorization_refresh; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth2_authorization_refresh ON public.oauth2_authorization USING btree (refresh_token_value);


--
-- Name: ix_oauth2_authorization_refresh_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth2_authorization_refresh_expiry ON public.oauth2_authorization USING btree (refresh_token_expires_at);


--
-- Name: ix_oauth2_authorization_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth2_authorization_state ON public.oauth2_authorization USING btree (state);


--
-- Name: ix_refresh_tokens_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_refresh_tokens_expiry ON public.refresh_tokens USING btree (expires_at) WHERE (revoked_at IS NULL);


--
-- Name: ix_refresh_tokens_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_refresh_tokens_session ON public.refresh_tokens USING btree (session_id);


--
-- Name: ix_users_email_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_users_email_active ON public.users USING btree (email) WHERE (deleted_at IS NULL);


--
-- Name: ix_users_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_users_status ON public.users USING btree (status) WHERE (deleted_at IS NULL);


--
-- Name: uq_device_sessions_cookie; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_device_sessions_cookie ON public.device_sessions USING btree (cookie_token_hash) WHERE (cookie_token_hash IS NOT NULL);


--
-- Name: uq_device_sessions_user_device; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_device_sessions_user_device ON public.device_sessions USING btree (user_id, device_id) WHERE ((device_id IS NOT NULL) AND (revoked_at IS NULL));


--
-- Name: ux_oauth2_registered_client_client_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_oauth2_registered_client_client_id ON public.oauth2_registered_client USING btree (client_id);


--
-- Name: auth_challenges auth_challenges_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_challenges
    ADD CONSTRAINT auth_challenges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: auth_identities auth_identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_identities
    ADD CONSTRAINT auth_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: device_sessions device_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_sessions
    ADD CONSTRAINT device_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: refresh_tokens refresh_tokens_replaced_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_replaced_by_fkey FOREIGN KEY (replaced_by) REFERENCES public.refresh_tokens(id) ON DELETE SET NULL;


--
-- Name: refresh_tokens refresh_tokens_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.device_sessions(id) ON DELETE CASCADE;


--
-- Name: refresh_tokens refresh_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
